const definitions = [
  ['SR-01','Never Guess or Invent','Safety',`Never invent unsupported fitment or product information.\n\nAccuracy takes priority over enrichment, title structure, and length.`],
  ['SR-02','Manual Override Protection','Protection',`A manually overridden or explicitly authoritative title must not be overwritten.`],
  ['SR-03','Preserve Critical Fitment','Fitment',`Do not remove verified fitment-critical information merely to shorten a title.\n\nPreserve when applicable:\n- Engine displacement\n- Engine code\n- Transmission code\n- VIN identifier\n- Drivetrain\n- Transmission speed/type\n- Placement\n- Side\n- Body style when fitment-relevant\n- Trim when fitment-relevant\n- Illumination\n- Color / paint code when materially relevant\n- Component type\n- ECM\n- ABS\n- BCM\n- PCM\n- TCM\n- EVAP\n- HVAC\n- TPMS`],
  ['SR-04','Manufacturer Part Number Safety','Part Numbers',`Use Manufacturer Part Number only from approved authoritative structured data.\n\nNever treat Hollander interchange as OEM/Manufacturer Part Number.\n\nDo not prepend "OEM Part".`],
  ['SR-05','SKU Exactly Once at End','SKU',`SKU must appear exactly once.\n\nSKU belongs at the end.\n\nIf SKU appears elsewhere:\n- remove embedded occurrence\n- append one copy at the end`],
  ['SR-06','Prefix 257 #SKU Exception','SKU',`For applicable confirmed cluster/speedometer/gauge listings, #SKU is a valid SKU ending when a bare number could look like mileage.\n\n#SKU counts as SKU appearing exactly once.`],
  ['SR-07','80 Character Maximum','Length',`Maximum title length:\n\n80 characters\n\nNever truncate a word.`],
  ['SR-08','Over-Limit Reduction Order','Length',`When over 80 characters remove in this order:\n\n1. optional synonym enrichment\n2. redundant duplicate terminology\n3. low-value promotional/filler wording\n4. optional Manufacturer Part Number\n5. non-fitment trailing descriptors\n\nNever sacrifice essential fitment.`],
  ['SR-09','AC Formatting','Formatting',`Use:\n\nAC\n\nNever:\n\nA/C`],
  ['SR-10','Make / Model Case Safety','Formatting',`Ordinary Make/Model names should not remain improperly ALL CAPS.\n\nPreserve legitimate acronyms and alphanumeric designations.`],
  ['SR-11','Side Only When Verified','Fitment',`Never add Side unless supported by source data.\n\nDo not infer placement from what is common for that part.`],
  ['SR-12','Junk / Noise Cleanup','Cleanup',`Remove when not legitimate product information:\n- embedded non-SKU stock numbers\n- Hollander numbers represented as OEM/MPN\n- OEM Part\n- Used Auto\n- Redundant Part\n- User Defined where applicable\n- standalone Hollander noise\n- broken spacing\n- consecutive duplicate words\n- repeated duplicate part terminology\n\nDo not remove legitimate verified VIN/fitment simply because it resembles source noise.`],
  ['SR-13','Truthful Duplicate Handling','Duplicates',`SKU is the primary duplicate differentiator.\n\nNever manufacture false differences to make titles unique.\n\nA truthful duplicate is preferable to incorrect information.\n\nDo not add Used solely to break duplicates.`],
  ['SR-14','No-Degrade / Idempotency','Protection',`When authoritative source data has not changed, reprocessing should normally produce the same result.\n\nDo not replace an existing title if the proposal:\n- loses verified fitment\n- adds unsupported information\n- becomes materially less clear\n- duplicates terminology\n- becomes malformed\n- exceeds 80 characters\n- removes buyer-critical terminology\n- reduces accuracy\n\nIf proposed title would be worse, retain existing title.\n\nAssociated standardized reason:\n\nProposed title would degrade existing title`],
  ['SR-15','Final Validation','Validation',`Future runtime must validate:\n- no unsupported information invented\n- Long Block not introduced\n- Short Block not introduced\n- verified displacement preserved\n- engine code preserved\n- transmission code preserved\n- VIN preserved\n- drivetrain preserved\n- relevant protected acronyms retained\n- AC rather than A/C\n- Make/Model casing valid\n- no word truncation\n- Used not unnecessarily added\n- Side only when verified\n- SKU exactly once at end\n- Prefix-257 #SKU accepted\n- title <= 80 characters\n- Hollander interchange not represented as OEM/MPN\n- manual override not overwritten\n- ambiguous model not guessed\n- proposal not worse than current title`]
];

const canonicalRules = Object.freeze(definitions.map(([id,title,category,behavior], index) => Object.freeze({ id, title, category, behavior, order:index + 1, source:'client-v5', version:'v5', locked:true })));
function getTitleOptimizationSystemRules() { return canonicalRules.map(rule => ({ ...rule })); }
module.exports = { getTitleOptimizationSystemRules };
