const SEEDS = [
  ['general', 'General', 'General / Default', [['yearOrRange','Year / Year Range','field'],['make','Make','field'],['model','Model','field'],['part','Part','field'],['side','Side','field'],['keyFitmentDetail','Key Fitment Detail','field'],['manufacturerPartNumber','Manufacturer Part Number','field'],['sku','SKU','field']], 'Preferred default title ordering. Missing or unverified values must not be invented merely to fill the structure.'],
  ['engines', 'Engines', 'Engines', [['year','Year','field'],['make','Make','field'],['model','Model','field'],['engineLiteral','Engine','literal'],['engineSize','Size','field'],['engineCode','Engine Code','field'],['vinIdentifier','VIN','field'],['approvedDescriptor','Approved Descriptor','field'],['sku','SKU','field']], 'Use only for confirmed engine listings. Preserve verified engine displacement, engine code, VIN identifier, and other genuine fitment identifiers. Approved Descriptor remains subject to Restricted Terms and applicable Seymour Auto authorization.'],
  ['transmissions', 'Transmissions', 'Transmissions', [['year','Year','field'],['make','Make','field'],['model','Model','field'],['automaticTransmissionLiteral','Automatic Transmission','literal'],['transmissionSpeedType','Speed / Type','field'],['transmissionCode','Transmission Code','field'],['drivetrain','Drivetrain','field'],['sku','SKU','field']], 'Use only for confirmed transmission listings. Use verified transmission code, speed/type, and drivetrain when available.']
];
const SEED_BY_ID = new Map(SEEDS.map((s, i) => [`client-v5-${s[0]}`, { s, order: i + 1 }]));
const norm = value => typeof value === 'string' ? value.trim().replace(/\s+/g, ' ').toLocaleLowerCase('en-US') : '';
const seg = (key, label, kind, id) => ({ id: id || `segment-${Math.random().toString(36).slice(2, 10)}`, key, label, kind });
function seedTitleStructuresConfiguration({ now, actor } = {}) { const at = now || new Date().toISOString(), by = String(actor || 'system').trim() || 'system'; return { version: 1, structures: SEEDS.map((s, i) => ({ id: `client-v5-${s[0]}`, structureName: s[1], appliesTo: s[2], segments: s[3].map(x => seg(...x, `segment-${s[0]}-${x[0]}`)), enabled: true, origin: 'client-v5', seedOrder: i + 1, note: s[4], createdAt: at, createdBy: by, updatedAt: at, updatedBy: by, deletedAt: null, deletedBy: null })), updatedAt: at, updatedBy: by }; }
function validateStructure(rule, peers = []) {
  const issues = [], add = (field, message) => issues.push({ field, message });
  if (!rule || typeof rule !== 'object' || Array.isArray(rule)) return [{ field: 'structure', message: 'Structure must be an object.' }];
  if (typeof rule.id !== 'string' || !rule.id.trim()) add('id', 'Structure ID is required.');
  if (typeof rule.structureName !== 'string' || !rule.structureName.trim()) add('structureName', 'Structure Name is required.');
  if (typeof rule.appliesTo !== 'string' || !rule.appliesTo.trim()) add('appliesTo', 'Applies To is required.');
  if (!Array.isArray(rule.segments) || !rule.segments.length) add('segments', 'Add at least one segment.');
  const seen = new Set(); (rule.segments || []).forEach((item, i) => { if (!item || typeof item !== 'object' || !['field','literal'].includes(item.kind) || typeof item.label !== 'string' || !item.label.trim()) add(`segments.${i}`, 'Each segment needs a non-blank label and valid kind.'); const n = norm(item?.label); if (n && seen.has(n)) add(`segments.${i}`, 'Duplicate segment labels are not allowed.'); if (n) seen.add(n); });
  if (typeof rule.enabled !== 'boolean') add('enabled', 'Enabled must be on or off.');
  if (rule.note != null && typeof rule.note !== 'string') add('note', 'Notes must be text.');
  const n = norm(rule.structureName); if (n && peers.some(p => p && !p.deletedAt && p.id !== rule.id && norm(p.structureName) === n)) add('structureName', 'This Structure Name already exists.');
  return issues;
}
function validatePersisted(rule) { const issues = validateStructure(rule, []), add = (f, m) => issues.push({ field: f, message: m }); if (!['client-v5','custom'].includes(rule?.origin)) add('origin','Origin is invalid.'); if (rule?.origin === 'client-v5' && (!SEED_BY_ID.has(rule.id) || rule.seedOrder !== SEED_BY_ID.get(rule.id).order)) add('seedOrder','Client-v5 seed identity is invalid.'); if (rule?.origin === 'custom' && rule?.seedOrder != null) add('seedOrder','Custom structures cannot use a seed order.'); for (const f of ['createdAt','updatedAt']) if (typeof rule?.[f] !== 'string' || !Number.isFinite(Date.parse(rule[f]))) add(f,`${f} is invalid.`); for (const f of ['createdBy','updatedBy']) if (typeof rule?.[f] !== 'string' || !rule[f].trim()) add(f,`${f} is invalid.`); if (rule?.deletedAt != null && (typeof rule.deletedAt !== 'string' || !Number.isFinite(Date.parse(rule.deletedAt)))) add('deletedAt','Deleted timestamp is invalid.'); return issues; }
function hydrateTitleStructuresConfiguration(raw) { const structures = [], issues = [], quarantined = [], seen = new Map(); if (!raw || typeof raw !== 'object' || !Array.isArray(raw.structures)) return { structures, issues: [{ id: null, message: 'Saved Title Structure configuration is malformed.' }], quarantined: raw === undefined ? [] : [raw] }; raw.structures.forEach((entry, i) => { const id = entry?.id || `entry-${i + 1}`, errors = validatePersisted(entry), n = norm(entry?.structureName); if (!entry?.deletedAt && n) { const prior = seen.get(n) || []; prior.push(entry); seen.set(n, prior); } if (errors.length) { issues.push({ id, message: `${id}: ${errors.map(x => x.message).join(' ')}` }); quarantined.push(entry); } else structures.push(entry); }); for (const [name, group] of seen) if (group.length > 1) { const ids = new Set(group.map(x => x.id)); for (let i = structures.length - 1; i >= 0; i--) if (ids.has(structures[i].id)) { issues.push({ id: structures[i].id, message: `Duplicate Structure Name "${name}" conflicts across IDs: ${[...ids].join(', ')}.` }); quarantined.push(structures[i]); structures.splice(i, 1); } } return { structures, issues, quarantined }; }
function compare(a, b) { const as = a.origin === 'client-v5', bs = b.origin === 'client-v5'; if (as !== bs) return as ? -1 : 1; return as ? a.seedOrder - b.seedOrder : norm(a.structureName).localeCompare(norm(b.structureName)) || String(a.id).localeCompare(String(b.id)); }
function enabledTitleStructures(config = {}) { return (config.structures || []).filter(x => x && x.enabled && !x.deletedAt).sort(compare); }
module.exports = { seedTitleStructuresConfiguration, validateStructure, validatePersisted, hydrateTitleStructuresConfiguration, enabledTitleStructures, compare, norm };
