const REASONS = [
  'Missing verified year', 'Make cannot be verified', 'Model cannot be normalized safely',
  'Multiple year ranges require review', 'Part identity uncertain', 'Required engine fitment missing',
  'Transmission code cannot be verified', 'Conflicting source data',
  'Cannot preserve essential fitment within 80 characters', 'Proposed title would degrade existing title'
];
const normalizeReason = value => typeof value === 'string' ? value.trim().replace(/\s+/g, ' ').toLocaleLowerCase('en-US') : '';
const seedId = index => `client-v5-${String(index + 1).padStart(2, '0')}`;
function seedFlagReasonsConfiguration({ now, actor } = {}) { const at = now || new Date().toISOString(), by = String(actor || 'system').trim() || 'system'; return { version: 1, reasons: REASONS.map((reason,index)=>({ id:seedId(index), reason, note:null, enabled:true, required:true, origin:'client-v5', seedOrder:index+1, createdAt:at, createdBy:by, updatedAt:at, updatedBy:by, deletedAt:null, deletedBy:null })), updatedAt:at, updatedBy:by }; }
function validateFlagReason(reason, peers=[]) { const issues=[], add=(field,message)=>issues.push({field,message}); if(!reason||typeof reason!=='object'||Array.isArray(reason)) return [{field:'reason',message:'Flag Reason must be an object.'}]; if(typeof reason.id!=='string'||!reason.id.trim())add('id','Reason ID is required.'); if(typeof reason.reason!=='string'||!reason.reason.trim())add('reason','Reason is required.'); if(reason.note!=null&&typeof reason.note!=='string')add('note','Notes must be text.'); if(typeof reason.enabled!=='boolean')add('enabled','Enabled must be on or off.'); const n=normalizeReason(reason.reason); if(n&&peers.some(x=>x&&!x.deletedAt&&x.id!==reason.id&&normalizeReason(x.reason)===n))add('reason','This Flag Reason already exists.'); return issues; }
function validatePersisted(reason) { const issues=validateFlagReason(reason,[]), add=(f,m)=>issues.push({field:f,message:m}); if(!['client-v5','custom'].includes(reason?.origin))add('origin','Origin is invalid.'); if(reason?.origin==='client-v5'){ const i=Number(String(reason.id||'').replace('client-v5-',''))-1; if(!Number.isInteger(i)||seedId(i)!==reason.id||REASONS[i]!==reason.reason)add('reason','Required client-v5 reason identity is invalid.'); if(reason.seedOrder!==i+1)add('seedOrder','Required seed order is invalid.'); if(reason.required!==true)add('required','Required status is invalid.'); if(reason.enabled!==true)add('enabled','Required reasons must remain enabled.'); } else { if(reason?.required!==false)add('required','Custom reasons cannot be required.'); if(reason?.seedOrder!=null)add('seedOrder','Custom reasons cannot use seed order.'); } for(const f of ['createdAt','updatedAt'])if(typeof reason?.[f]!=='string'||!Number.isFinite(Date.parse(reason[f])))add(f,`${f} is invalid.`); for(const f of ['createdBy','updatedBy'])if(typeof reason?.[f]!=='string'||!reason[f].trim())add(f,`${f} is invalid.`); if(reason?.deletedAt!=null&&(typeof reason.deletedAt!=='string'||!Number.isFinite(Date.parse(reason.deletedAt))))add('deletedAt','deletedAt is invalid.'); if(reason?.deletedAt!=null&&(typeof reason.deletedBy!=='string'||!reason.deletedBy.trim()))add('deletedBy','deletedBy is required.'); return issues; }
function compareFlagReasons(a,b){ const as=a.origin==='client-v5',bs=b.origin==='client-v5'; if(as!==bs)return as?-1:1; return as?a.seedOrder-b.seedOrder||String(a.id).localeCompare(String(b.id)):normalizeReason(a.reason).localeCompare(normalizeReason(b.reason))||String(a.id).localeCompare(String(b.id)); }
function hydrateFlagReasonsConfiguration(raw){ if(!raw||typeof raw!=='object'||Array.isArray(raw)||!Array.isArray(raw.reasons))return{reasons:[],issues:[{id:null,message:'Saved Flag Reasons configuration is malformed.'}],quarantined:raw===undefined?[]:[raw]}; const items=raw.reasons.map((entry,index)=>({entry,index,errors:validatePersisted(entry)})), ids=new Map(), names=new Map(); for(const item of items){const id=item.entry?.id;if(typeof id==='string')ids.set(id,[...(ids.get(id)||[]),item]);if(!item.entry?.deletedAt){const name=normalizeReason(item.entry?.reason);if(name)names.set(name,[...(names.get(name)||[]),item]);}} for(const[id,g]of ids)if(g.length>1)g.forEach(x=>x.errors.push({field:'id',message:`Duplicate reason ID ${id}.`})); for(const[name,g]of names)if(g.length>1){const ids=g.map(x=>x.entry?.id||`entry-${x.index+1}`).join(', ');g.forEach(x=>x.errors.push({field:'reason',message:`Duplicate normalized reason "${name}" conflicts across reason IDs: ${ids}.`}));} const reasons=[],issues=[],quarantined=[]; for(const item of items){const id=item.entry?.id||`entry-${item.index+1}`;if(item.errors.length){issues.push({id,message:`${id}: ${item.errors.map(x=>x.message).join(' ')}`});quarantined.push(item.entry);}else reasons.push(item.entry);} return{reasons:reasons.sort(compareFlagReasons),issues,quarantined}; }
const enabledFlagReasons=config=>(Array.isArray(config.reasons)?config.reasons:[]).filter(x=>x&&x.enabled&&!x.deletedAt).sort(compareFlagReasons);
module.exports={ REASONS, normalizeReason, seedFlagReasonsConfiguration, validateFlagReason, hydrateFlagReasonsConfiguration, enabledFlagReasons, compareFlagReasons };
